services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
    container_name: bobscorndb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - bobscorn-network

networks:
  bobscorn-network:
    driver: bridge